{{- if .Values.ingress.enabled -}}
{{- $fullName := include "race-management-car-gateway.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $host := ternary (printf "%s.%s" .Values.ingress.subdomain .Values.ingress.domain) (printf "%s-%s.%s" .Values.ingress.subdomain .Values.ingress.environment .Values.ingress.domain) (eq .Values.ingress.environment "prod") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "race-management-car-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /{{ .Values.ingress.pathPrefix }}/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
