<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>028975bb-5b61-4bec-a13e-5e1034cf0977</UserSecretsId>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
		<PackageReference Include="Keycloak.AuthServices.Authorization" Version="3.0.0" />
		<PackageReference Include="Keycloak.AuthServices.Authentication" Version="3.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.System" Version="9.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="StackExchange.Redis" Version="2.13.1" />
		<PackageReference Include="NLog.Extensions.Logging" Version="6.1.3" />
		<PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.6.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="10.0.8" />
		<PackageReference Include="TypeGen" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Common\Common.csproj" />
		<ProjectReference Include="..\Cloud.Shared\Cloud.Shared.csproj" />
	</ItemGroup>

	<Target Name="GenerateTypeScriptModels" AfterTargets="Build">
		<Exec Command="dotnet tool restore" WorkingDirectory="$(MSBuildProjectDirectory)\..\..\.." />
		<Exec Command="dotnet tool run dotnet-typegen generate" WorkingDirectory="$(MSBuildProjectDirectory)" />
	</Target>

</Project>
