// <auto-generated />
using System;
using Cloud.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cloud.Shared.Database.Migrations
{
    [DbContext(typeof(RaceManagementContext))]
    [Migration("20260527013523_AddTeamSelectedRaceId")]
    partial class AddTeamSelectedRaceId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cloud.Shared.Database.Models.Alarms.ActiveAlarmRow", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("CarNumber")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid>("AlarmDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAcknowledgedTimestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastActivatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TeamId", "CarNumber", "AlarmDefinitionId");

                    b.HasIndex("AlarmDefinitionId");

                    b.HasIndex("TeamId", "IsActive");

                    b.ToTable("ActiveAlarms");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.Alarms.AlarmDefinitionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlarmStatusChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("CarNumber")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("DisplayChannelSourceColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatementJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeAfterAckToDisplaySecs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "CarNumber");

                    b.ToTable("AlarmDefinitions");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.Alarms.AlarmEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AlarmDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlarmDefinitionId");

                    b.HasIndex("TeamId", "CarNumber", "AlarmDefinitionId", "Timestamp");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.Car", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TeamId", "Number");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.CarConfigurationTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Car")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConfigurationSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastUpdatedOnCarTimestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "Car");

                    b.ToTable("CarConfiguration");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.ChannelStatusTableColumnConfiguration", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ChannelDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameOverride")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "UserId", "ChannelDefinitionId");

                    b.ToTable("ChannelStatusTableColumnConfiguration");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.ChannelStatusTableConfiguration", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("TeamId", "UserId");

                    b.ToTable("ChannelStatusTableConfigurations");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.FuelAnalysis.CalibrationFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("TeamId", "CarNumber", "EffectiveAt");

                    b.ToTable("CalibrationFactors");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.FuelAnalysis.FuelWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("ClosedBySessionEnd")
                        .HasColumnType("boolean");

                    b.Property<int?>("EndRefuelEventId")
                        .HasColumnType("integer");

                    b.Property<double?>("ObservedConsumptionGalPerMin")
                        .HasColumnType("double precision");

                    b.Property<double?>("ObservedDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("StartRefuelEventId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EndRefuelEventId");

                    b.HasIndex("RaceId");

                    b.HasIndex("StartRefuelEventId");

                    b.HasIndex("TeamId", "CarNumber", "RaceId")
                        .IsUnique()
                        .HasFilter("\"ClosedAt\" IS NULL");

                    b.HasIndex("TeamId", "CarNumber", "RaceId", "OpenedAt");

                    b.ToTable("FuelWindows");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.FuelAnalysis.RefuelEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnchorFlags")
                        .HasColumnType("integer");

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("ConfidenceTier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EcuResetState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("EnteredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("EnteredFuelGallons")
                        .HasColumnType("double precision");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("TeamId", "CarNumber", "RaceId", "DetectedAt");

                    b.ToTable("RefuelEvents");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.FuelAnalysis.Stint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("DriverId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FuelWindowId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FuelWindowId");

                    b.HasIndex("RaceId");

                    b.HasIndex("TeamId", "CarNumber", "RaceId", "StartAt");

                    b.ToTable("Stints");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.FuelAnalysis.TeamFuelDefaults", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<double>("Code35Multiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("Code60Multiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("GreenMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("HighConfidenceThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("RedMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("YellowMultiplier")
                        .HasColumnType("double precision");

                    b.HasKey("TeamId");

                    b.ToTable("TeamFuelDefaults");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RedMistEventId")
                        .HasColumnType("integer");

                    b.Property<int?>("RedMistOrganizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.SiteSettings", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("RedMistClientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RedMistClientSecret")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("TeamId");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SelectedRaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.UserRoleMapping", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("TeamId", "Email");

                    b.ToTable("UserRoleMappings");
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.Alarms.ActiveAlarmRow", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Alarms.AlarmDefinitionRow", null)
                        .WithMany()
                        .HasForeignKey("AlarmDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cloud.Shared.Database.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "CarNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.Alarms.AlarmDefinitionRow", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.Alarms.AlarmEventRow", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Alarms.AlarmDefinitionRow", null)
                        .WithMany()
                        .HasForeignKey("AlarmDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cloud.Shared.Database.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "CarNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.Car", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.CarConfigurationTable", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.ChannelStatusTableColumnConfiguration", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.ChannelStatusTableConfiguration", null)
                        .WithMany("Columns")
                        .HasForeignKey("TeamId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.ChannelStatusTableConfiguration", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.FuelAnalysis.CalibrationFactor", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cloud.Shared.Database.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "CarNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.FuelAnalysis.FuelWindow", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.FuelAnalysis.RefuelEvent", null)
                        .WithMany()
                        .HasForeignKey("EndRefuelEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cloud.Shared.Database.Models.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cloud.Shared.Database.Models.FuelAnalysis.RefuelEvent", null)
                        .WithMany()
                        .HasForeignKey("StartRefuelEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cloud.Shared.Database.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "CarNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.FuelAnalysis.RefuelEvent", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cloud.Shared.Database.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "CarNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.FuelAnalysis.Stint", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.FuelAnalysis.FuelWindow", null)
                        .WithMany()
                        .HasForeignKey("FuelWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cloud.Shared.Database.Models.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cloud.Shared.Database.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "CarNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.FuelAnalysis.TeamFuelDefaults", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.Race", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.SiteSettings", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.UserRoleMapping", b =>
                {
                    b.HasOne("Cloud.Shared.Database.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cloud.Shared.Database.Models.ChannelStatusTableConfiguration", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
