<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="TypeGen" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Channels\Channels.csproj" />
	</ItemGroup>

	<Target Name="GenerateTypeScriptModels" AfterTargets="Build">
		<Exec Command="dotnet tool restore" WorkingDirectory="$(MSBuildProjectDirectory)\..\.." />
		<Exec Command="dotnet tool run dotnet-typegen generate" WorkingDirectory="$(MSBuildProjectDirectory)" />
	</Target>

</Project>
